<script lang="ts">
  import { onMount } from 'svelte';
  import { browser } from '$app/environment';

  const STORAGE_KEY = 'seizure-warning-agreed';

  let show = $state(false);
  let submitting = $state(false);

  onMount(() => {
    if (!localStorage.getItem(STORAGE_KEY)) {
      show = true;
    }
  });

  async function respond(agreed: boolean) {
    if (submitting) return;
    submitting = true;

    try {
      await fetch('/api/seizure-warning', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          agreed,
          screenWidth: window.screen?.width ?? null,
          screenHeight: window.screen?.height ?? null,
          language: navigator.language || '',
          referrer: document.referrer || null
        })
      });
    } catch {
      // Log failure shouldn't block user action
    }

    if (agreed) {
      localStorage.setItem(STORAGE_KEY, '1');
      show = false;
    } else {
      window.location.href = 'https://www.google.com';
    }
  }
</script>

{#if show}
  <div class="sw-backdrop">
    <div class="sw-panel">
      <!-- Nails -->
      <div class="nails"><div class="nail"></div><div class="nail"></div></div>
      <div class="nails nails-bottom"><div class="nail"></div><div class="nail"></div></div>

      <!-- Warning icon -->
      <div class="icon-wrap">
        <svg width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
          <path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3Z" />
          <path d="M12 9v4" />
          <path d="M12 17h.01" />
        </svg>
      </div>

      <h2 class="sw-title">Photosensitivity Warning</h2>

      <p class="sw-body">
        This application displays rapidly flashing patterns, strobing colors, and high-contrast animations generated by cellular automata.
      </p>
      <p class="sw-body">
        These visual effects <strong>may trigger seizures</strong> in people with photosensitive epilepsy or related conditions. Viewer discretion is advised.
      </p>

      <button
        class="btn-agree"
        disabled={submitting}
        onclick={() => respond(true)}
      >
        {submitting ? 'Please wait...' : 'I Understand & Agree'}
      </button>

      <button
        class="btn-disagree"
        disabled={submitting}
        onclick={() => respond(false)}
      >
        I Do Not Agree
      </button>
    </div>
  </div>
{/if}

<style>
  .sw-backdrop {
    position: fixed;
    inset: 0;
    z-index: 9999;
    display: flex;
    align-items: center;
    justify-content: center;
    background: rgba(0, 0, 0, 0.85);
    backdrop-filter: blur(8px);
  }

  .sw-panel {
    position: relative;
    width: 100%;
    max-width: 440px;
    margin: 0 16px;
    padding: 32px 28px 24px;
    background-color: #1c1917;
    background-image:
      repeating-linear-gradient(
        0deg,
        transparent,
        transparent 10px,
        rgba(68, 64, 60, 0.1) 10px,
        rgba(68, 64, 60, 0.1) 11px
      );
    border: 2px solid #44403c;
    border-radius: 8px;
    box-shadow: 0 25px 60px rgba(0, 0, 0, 0.5);
    text-align: center;
  }

  /* Nails */
  .nails {
    position: absolute;
    top: 8px;
    left: 12px;
    right: 12px;
    display: flex;
    justify-content: space-between;
    pointer-events: none;
  }

  .nails-bottom {
    top: auto;
    bottom: 8px;
  }

  .nail {
    width: 6px;
    height: 6px;
    background: #78716c;
    border-radius: 50%;
    box-shadow: inset 0 -1px 0 rgba(0,0,0,0.5), 0 0 0 1px rgba(0,0,0,0.3);
  }

  /* Icon */
  .icon-wrap {
    display: flex;
    justify-content: center;
    margin-bottom: 12px;
    color: #facc15;
    filter: drop-shadow(0 0 8px rgba(250, 204, 21, 0.4));
  }

  /* Title */
  .sw-title {
    font-family: 'Space Grotesk', sans-serif;
    font-size: 22px;
    font-weight: 700;
    color: #f5f5f4;
    margin: 8px 0 16px;
  }

  .sw-body {
    font-family: 'Space Grotesk', sans-serif;
    font-size: 15px;
    color: #a8a29e;
    line-height: 1.6;
    margin: 0 0 12px;
  }

  .sw-body strong {
    color: #facc15;
    font-weight: 600;
  }

  /* Agree button */
  .btn-agree {
    display: block;
    width: 100%;
    margin-top: 20px;
    padding: 14px 16px;
    font-family: 'Space Mono', monospace;
    font-size: 13px;
    font-weight: 700;
    letter-spacing: 0.08em;
    text-transform: uppercase;
    color: #1c1917;
    background: #facc15;
    border: none;
    border-radius: 6px;
    cursor: pointer;
    transition: background 0.15s, box-shadow 0.15s;
  }

  .btn-agree:hover:not(:disabled) {
    background: #fde047;
    box-shadow: 0 0 12px rgba(250, 204, 21, 0.3);
  }

  .btn-agree:disabled {
    opacity: 0.6;
    cursor: not-allowed;
  }

  /* Disagree button */
  .btn-disagree {
    display: inline-block;
    margin-top: 14px;
    padding: 0;
    font-family: 'Space Grotesk', sans-serif;
    font-size: 13px;
    color: #57534e;
    background: none;
    border: none;
    cursor: pointer;
    transition: color 0.15s;
  }

  .btn-disagree:hover:not(:disabled) {
    color: #a8a29e;
  }

  .btn-disagree:disabled {
    cursor: not-allowed;
  }
</style>
